### ISSUE TITLE
About Fall 2024 Project 5

### ISSUE THREAD

**Issue by sakiDisk** [mgiannopoulos24/Artificial-Intelligence#1]
It seems that '**class Attention(Module):**' is not implemented, which is related about '**EXTRA CREDIT Question 6 (1 point): Attention**'.
Sincerely hoping that you can fill this so that we will have a better model.
THANKS!!!

**Comment by mgiannopoulos24** [comment]
Hey there! I plan on doing it soon. I just took some time off for Christmas.

**Comment by mgiannopoulos24** [comment]
Hi @sakiDisk ,

I’ve implemented Question 6 from Fall 2024 Project 5. If you found the repository useful, I would appreciate it if you could give it a star.

Thanks in advance, and happy holidays!

**Comment by sakiDisk** [comment]
It works!!! Sincerely thanks for your contribution!!!
